#!/bin/bash

printUsage() {
    echo "Usage: $0 <database> [local database name]"
    exit 1;
}

if [ -z $1 ]; then
    printUsage
fi

if ! [ $(command -v mysqlshow) ]; then
    echo 'Error: $0: mysqlshow is not installed. Install mysql-client or mariadb-client'
fi

if ! [ $(command -v pv) ]; then
    echo 'Error: $0: pv is not installed. Install pv'
fi

if ! [ $(command -v gunzip) ]; then
    echo 'Error: $0: gunzip is not installed. Install gunzip'
fi

database=$1
local_db_name=${2:-$database}
database_backup="$1_backup"
local_database_exists=$(mysqlshow -u root -proot -h 127.0.0.1 $local_db_name | grep -v Wildcard | grep -o $local_db_name)

if [ "$local_database_exists" == "$local_db_name" ]; then
    mysql -u root -proot -h 127.0.0.1 -e "drop database if exists $database_backup; create database $database_backup;"
    for table in `mysql -u root -proot -h 127.0.0.1 -s -N -e "show tables from $database;"`;
        do mysql -u root -proot -h 127.0.0.1 -s -N -e "rename table $database.$table to $database_backup.$table;";
    done;
fi

rsync -ravP tomc@dev2:/home/dumpy/$database.sql.gz /tmp/$database.sql.gz

mysql -u root -proot -h 127.0.0.1 -e "create database if not exists $database;"

pv /tmp/$database.sql.gz | gunzip | mysql -u root -proot -h 127.0.0.1 $local_db_name

rm /tmp/$database.sql.gz
