#!/bin/bash

fod_branch=$1
framework_branch=$2

if [ "$fod_branch" == "." ]; then
    fod_branch=$(git -C ~/git/fod rev-parse --abbrev-ref HEAD)
fi

if [ "$framework_branch" == "." ]; then
    framework_branch=$(git -C ~/git/framework rev-parse --abbrev-ref HEAD)
fi

cd ~/git/ansible

ansible-playbook deploy.yml -e fod_branch=$fod_branch -e framework_branch=$framework_branch;
