#!/bin/bash

DATE=$(date +%Y-%m-%d)
LOG=${1:-application};
shift;

if [ $LOG == 'rep' ] || [ $LOG == 'replication' ]; then
    LOG="replication_checker";
fi
if [ $LOG == 'app' ]; then
    LOG="application";
fi

if [ $LOG != 'api' ] && [ $LOG != 'allocation' ] && [ $LOG != 'application' ] && [ $LOG != 'email' ] && [ $LOG != 'replication_checker' ]; then
    echo 'Invalid log type. Valid selections are: api, app[lication], allocation, email, rep[lication]'
    exit 1;
fi

FILE="/home/tom/git/fod/logs/fod.docker/$LOG/$DATE.log"

if [ -f "$FILE" ]; then
    tail $LOG $@ $FILE
else
    echo 'No logs for today'
fi
