#!/bin/bash

# Manage git repos remotely. Should hook into git as an extension ala "git repo"

function printUsage {
	echo "Usage: $0 [-a|--area] [-c|--copy]";
	exit 1;
}

NAME=""
DESC=""
PRIVATE=false

if [[ "$1" =~ ^((-{1,2})([Hh]$|[Hh][Ee][Ll][Pp]))$ ]]; then
    printUsage;
    exit 1
else
	while [[ $# -gt 0 ]]; do
		opt="$1"
		shift;
		current_arg="$1"

		if [[ "$current_arg" =~ ^-{1,2}.* ]]; then
			echo "test";
		fi

		case "$opt" in
			"-n"|"--name"		) NAME=$1; shift;;
			"-d"|"--description"	) DESC=$1; shift;;
			"-p"|"--private"	) PRIVATE=true; shift;;
			*			) echo "Error: $0: Invalid option \"$opt\"" >&2
						  exit 1;;
		esac
	done
fi

POST_DATA='{"name":"$NAME","description":"$DESC","private":$PRIVATE}'

curl -H 'Accept: application/json' \
     -H 'Content-Type: application/json' \
     -X POST --data "$POST_DATA" https://api.github.com/tomcorby/repos
