#!/bin/bash

# Dodgy AF. Need a better way of doing this

PHP_7_PACKAGES="php-bcmath php-cli-prompt php-common php-composer-ca-bundle php-composer-semver php-composer-spdx-licenses php-curl php-gd php-imap php-json-schema php-mbstring php-psr-log php-snmp php-soap php-symfony-console php-symfony-debug php-symfony-filesystem php-symfony-finder php-symfony-polyfill-mbstring php-symfony-process php-xml php-zip"

PHP_PACKAGES=$(dpkg --get-selections | grep 'php-' | sed 's/\s.*$//' | sed ':a;N;$!ba;s/\n/ /g')
LIBAPACHE_VERSION=$(dpkg --get-selections | grep libapache2-mod | sed 's/\s.*$//')
CURRENT_PHP_VERSION=$(dpkg --get-selections | grep -E "^php[0-9]\.[0-9][^-]" | sed 's/\s.*$//')
DESIRED_PHP_VERSION="php$1"

echo "sudo apt remove $CURRENT_PHP_VERSION $LIBAPACHE_VERSION $PHP_PACKAGES"
echo "sudo apt install $DESIRED_PHP_VERSION libapache2-mod-$DESIRED_PHP_VERSION $PHP_PACKAGES"
