#!/bin/bash

DIR=/home/tom
LINE_LIMIT=1

cd $DIR;

# is spotify-ripper already running
if pgrep -x spotify-ripper > /dev/null; then
    echo "Already running"
    exit 1;
fi

# do we have a list file
if [ ! -f list ]; then
    echo "No list file exists"
    exit 2;
fi

#split list file up
split -l$LINE_LIMIT list list
rm list

#do the deed
for f in list[a-z][a-z]; do
    echo $f;
    spotify-ripper $f;
    rm $f;
done

mv log $(date '+%Y-%m-%d_%H:%M').log
mv faillog $(date '+%Y-%m-%d_%H:%M').faillog

rclone move -v $DIR/music onedrive:/Music

cd $DIR/music

find . -type d -empty -delete

exit;
