#!/bin/bash

DIR=/home/tom
LINE_LIMIT=1

cd $DIR;

# is spotify-ripper already running
if pgrep -x spotify-ripper > /dev/null; then
    echo "Already running"
    exit 1;
fi

if ! [ -x "$(command -v rclone >/dev/null 2>&1)" ]; then
    echo "rclone missing. To install run curl https://rclone.org/install.sh | bash"
    exit 2;
fi

# do we have a list file
if [ ! -f list ]; then
    echo "No list file exists"
    exit 3;
fi

#split list file up
split -l$LINE_LIMIT list list
NOWDATE=$(date '+%Y-%m-%d_%H:%M')

if [ ! -d history ]; then
    mkdir history
fi

mv list list-$NOWDATE

if [ ! -d music ]; then
    mkdir music
fi

#do the deed
for f in list[a-z][a-z]; do
    echo $f;
    spotify-ripper $f;
    rm $f;
done

mv log history/$NOWDATE.log
mv faillog history/$NOWDATE.faillog

rclone move -v $DIR/music onedrive:/Music

cd $DIR/music

find . -type d -empty -delete

exit;
