#!/bin/bash

if [ -z $1 ]; then
    setstatus=on
else
    setstatus=off
fi

if [ $setstatus == "on" ]; then
    # change monitor to windows screen
    sudo ddccontrol -r 0x60 -w 17 dev:/dev/i2c-7 > /dev/null 2>&1

    # enable synergy
    synergys
else
    # change monitor to linux screen
    sudo ddccontrol -r 0x60 -w 1 dev:/dev/i2c-7 > /dev/null 2>&1

    # stop synergy
    sudo killall synergys
fi
