#!/bin/bash

vpnAction=${1:-on};
scriptPath="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

if [ "$vpnAction" != "on" ] && [ "$vpnAction" != "off" ]; then
    vpnAction=on
fi

if [ -f "$scriptPath/.env" ]; then
    source "$scriptPath/.env"
else
    echo -e "No environment file found"
    exit 1;
fi

if [ "$vpnAction" = "on" ]; then
    barracudavpn --start --login $VPN_USERNAME --serverpwd $VPN_PASSWORD
else
    barracudavpn --stop
fi
